class LottieRule {
  final String asset;
  final List<String> keywords;

  const LottieRule(this.asset, this.keywords);
}

const String defaultAnimationAsset = 'assets/gifs/kitchen.gif';

const List<String> fallbackAnimations = [
  'assets/gifs/kitchen.gif',
  'assets/gifs/fork-knife.gif',
  'assets/gifs/cooking-apron.gif',
  'assets/gifs/cooker-hood.gif',
  'assets/gifs/toque-cooking-hat.gif',
];

final List<LottieRule> lottieRules = _buildLottieRules();

List<LottieRule> _buildLottieRules() => [
  LottieRule('assets/gifs/apple-pie.gif', _keywords([
    'apple pie',
    'apple',
    'manzana',
    'tarta',
    'pastel',
    'pie',
    'postre de manzana',
    'apple dessert',
  ])),
  LottieRule('assets/gifs/aubergine.gif', _keywords([
    'berenjena',
    'aubergine',
    'eggplant',
    'berenjenas asadas',
  ])),
  LottieRule('assets/gifs/avocado.gif', _keywords([
    'avocado',
    'aguacate',
    'palta',
    'guacamole',
  ])),
  LottieRule('assets/gifs/back-yard.gif', _keywords([
    'patio',
    'jardin',
    'exterior',
    'backyard',
    'parrillada al aire libre',
  ])),
  LottieRule('assets/gifs/bake-cooker.gif', _keywords([
    'hornea',
    'hornear',
    'horno',
    'precalienta',
    'precalentar',
    'bake',
    'cocer al horno',
    'receta al horno',
  ])),
  LottieRule('assets/gifs/barbecue.gif', _keywords([
    'barbacoa',
    'barbecue',
    'parrilla',
    'asar a la parrilla',
    'brasas al aire libre',
  ])),
  LottieRule('assets/gifs/basil.gif', _keywords([
    'albahaca',
    'basil',
    'hierbas frescas',
    'hojas aromaticas',
  ])),
  LottieRule('assets/gifs/blender.gif', _keywords([
    'licua',
    'licuado',
    'licuadora',
    'tritura',
    'triturar',
    'pure',
    'batido',
    'mezcla cremosa',
  ])),
  LottieRule('assets/gifs/bowl-chopsticks.gif', _keywords([
    'bol con palillos',
    'chopsticks',
    'palillos',
    'ramen',
    'fideos',
    'noodles bowl',
  ])),
  LottieRule('assets/gifs/bowl-of-soup.gif', _keywords([
    'sopa',
    'caldo',
    'sopera',
    'sopero',
    'sopa caliente',
  ])),
  LottieRule('assets/gifs/burger-alt.gif', _keywords([
    'hamburguesa',
    'burger',
    'sandwich de carne',
    'cheeseburger',
  ])),
  LottieRule('assets/gifs/burger-hamburger.gif', _keywords([
    'hamburguesa',
    'burger',
    'carne molida',
    'hamburguesa casera',
  ])),
  LottieRule('assets/gifs/butter.gif', _keywords([
    'mantequilla',
    'butter',
    'untar mantequilla',
    'barra de mantequilla',
  ])),
  LottieRule('assets/gifs/charcoal.gif', _keywords([
    'carbon',
    'brasas',
    'encender fuego',
    'charcoal',
    'fogata',
  ])),
  LottieRule('assets/gifs/cheese.gif', _keywords([
    'queso',
    'cheese',
    'rallar queso',
    'queso rallado',
  ])),
  LottieRule('assets/gifs/chopsticks.gif', _keywords([
    'palillos',
    'chopsticks',
    'comer con palillos',
    'utensilios asiaticos',
  ])),
  LottieRule('assets/gifs/cleaver-knife.gif', _keywords([
    'cuchillo grande',
    'hacha',
    'cleaver',
    'picar carne gruesa',
    'cuchillo de carnicero',
  ])),
  LottieRule('assets/gifs/coconut.gif', _keywords([
    'coco',
    'coconut',
    'leche de coco',
    'ralladura de coco',
  ])),
  LottieRule('assets/gifs/coffee-machine.gif', _keywords([
    'cafe',
    'cafetera',
    'coffee',
    'espresso',
    'taza de cafe',
  ])),
  LottieRule('assets/gifs/cooker-hood.gif', _keywords([
    'campana',
    'extractor',
    'cocina ventilacion',
    'campana extractora',
  ])),
  LottieRule('assets/gifs/cookies-milk.gif', _keywords([
    'galletas y leche',
    'merienda',
    'cookies milk',
    'snack dulce',
  ])),
  LottieRule('assets/gifs/cookies.gif', _keywords([
    'galletas',
    'cookies',
    'hornear galletas',
    'masa de galletas',
  ])),
  LottieRule('assets/gifs/cooking-apron.gif', _keywords([
    'delantal',
    'apron',
    'ponte el delantal',
    'ropa de cocina',
  ])),
  LottieRule('assets/gifs/corkscrew-wine.gif', _keywords([
    'sacacorchos',
    'vino',
    'abrir botella',
    'descorchar',
  ])),
  LottieRule('assets/gifs/corn-cob.gif', _keywords([
    'maiz',
    'mazorca',
    'corn',
    'elote',
  ])),
  LottieRule('assets/gifs/corn-dog.gif', _keywords([
    'corn dog',
    'perrito de maiz',
    'hot dog de maiz',
    'feria de comida',
  ])),
  LottieRule('assets/gifs/culinary-and-heritage-expeditions.gif', _keywords([
    'expedicion',
    'aventura culinaria',
    'heritage',
    'viaje gastronomico',
    'ruta de sabores',
  ])),
  LottieRule('assets/gifs/donut.gif', _keywords([
    'dona',
    'donut',
    'rosquilla',
    'glaseado dulce',
  ])),
  LottieRule('assets/gifs/egg-tray.gif', _keywords([
    'huevera',
    'bandeja de huevos',
    'egg tray',
    'carton de huevos',
  ])),
  LottieRule('assets/gifs/eggs.gif', _keywords([
    'huevo',
    'huevos',
    'rompe el huevo',
    'huevos frescos',
  ])),
  LottieRule('assets/gifs/electric-stovetop.gif', _keywords([
    'placa electrica',
    'cocina electrica',
    'stovetop',
    'vitroceramica',
    'placa de induccion',
  ])),
  LottieRule('assets/gifs/electric-teapot.gif', _keywords([
    'hervidor',
    'tetera electrica',
    'electric kettle',
    'te caliente',
    'hervir agua',
  ])),
  LottieRule('assets/gifs/fastfood.gif', _keywords([
    'comida rapida',
    'fast food',
    'combo',
    'menu express',
  ])),
  LottieRule('assets/gifs/female-cook.gif', _keywords([
    'cocinera',
    'chef mujer',
    'female cook',
    'chef femenina',
  ])),
  LottieRule('assets/gifs/food-as-resources.gif', _keywords([
    'suministros',
    'provisiones',
    'despensa',
    'abastece',
    'reserva de comida',
  ])),
  LottieRule('assets/gifs/food-plate-warm-cover.gif', _keywords([
    'campana metalica',
    'mantener caliente',
    'servir cubierto',
    'plato cubierto',
  ])),
  LottieRule('assets/gifs/food-truck.gif', _keywords([
    'camioneta de comida',
    'food truck',
    'venta ambulante',
    'camion gastronómico',
  ])),
  LottieRule('assets/gifs/fork-knife.gif', _keywords([
    'tenedor y cuchillo',
    'cubre mesa',
    'cuberteria',
    'set de cubiertos',
  ])),
  LottieRule('assets/gifs/french-fries-chips.gif', _keywords([
    'patatas fritas',
    'papas fritas',
    'french fries',
    'papas crujientes',
  ])),
  LottieRule('assets/gifs/french-macarons.gif', _keywords([
    'macarons',
    'macarrones franceses',
    'dulce frances',
    'postre elegante',
  ])),
  LottieRule('assets/gifs/fridge.gif', _keywords([
    'nevera',
    'refrigerar',
    'frigorifico',
    'enfria',
    'refrigerador',
  ])),
  LottieRule('assets/gifs/fried-egg.gif', _keywords([
    'huevo frito',
    'fried egg',
    'estrella huevo',
    'yema dorada',
  ])),
  LottieRule('assets/gifs/fritters.gif', _keywords([
    'buñuelos',
    'fritters',
    'freir masa',
    'masa frita',
  ])),
  LottieRule('assets/gifs/garlic.gif', _keywords([
    'ajo',
    'garlic',
    'ajos',
    'diente de ajo',
  ])),
  LottieRule('assets/gifs/gas-burner.gif', _keywords([
    'hervir',
    'ebullicion',
    'burbujea',
    'fuego alto',
    'llama viva',
  ])),
  LottieRule('assets/gifs/gas-stove.gif', _keywords([
    'cocina de gas',
    'fuego medio',
    'gas',
    'hornilla',
  ])),
  LottieRule('assets/gifs/gingerbread-man.gif', _keywords([
    'pan de jengibre',
    'gingerbread',
    'galleta de jengibre',
    'muñeco de jengibre',
  ])),
  LottieRule('assets/gifs/gluten-free.gif', _keywords([
    'sin gluten',
    'gluten free',
    'celiaco',
    'apto celiacos',
  ])),
  LottieRule('assets/gifs/herbs.gif', _keywords([
    'hierbas',
    'herbs',
    'aromaticas',
    'mezcla de hierbas',
  ])),
  LottieRule('assets/gifs/honey.gif', _keywords([
    'miel',
    'honey',
    'endulza con miel',
    'miel de abeja',
  ])),
  LottieRule('assets/gifs/hotdog.gif', _keywords([
    'hotdog',
    'perro caliente',
    'pancho',
    'hot dog con salsa',
  ])),
  LottieRule('assets/gifs/jam-jar.gif', _keywords([
    'mermelada',
    'confitura',
    'jarra jam',
    'frasco de mermelada',
  ])),
  LottieRule('assets/gifs/kitchen-scale.gif', _keywords([
    'balanza',
    'peso',
    'kitchen scale',
    'pesar ingredientes',
    'precisión al pesar',
  ])),
  LottieRule('assets/gifs/kitchen.gif', _keywords([
    'cocina',
    'kitchen',
    'espacio cocina',
    'zona de coccion',
  ])),
  LottieRule('assets/gifs/knife.gif', _keywords([
    'cortar',
    'cuchillo',
    'picar',
    'trocear',
    'juliana',
    'rebanar',
    'filetear verduras',
  ])),
  LottieRule('assets/gifs/ladle.gif', _keywords([
    'cucharón',
    'cucharon',
    'ladle',
    'servir sopa',
    'cazo sopero',
  ])),
  LottieRule('assets/gifs/lobster.gif', _keywords([
    'langosta',
    'marisco',
    'lobster',
    'platillo gourmet',
  ])),
  LottieRule('assets/gifs/male-cook.gif', _keywords([
    'cocinero',
    'chef',
    'male cook',
    'chef masculino',
  ])),
  LottieRule('assets/gifs/meat-grinder.gif', _keywords([
    'molino de carne',
    'picadora',
    'grinder',
    'carne molida',
    'maquina de picar',
  ])),
  LottieRule('assets/gifs/meat.gif', _keywords([
    'carne',
    'meat',
    'proteina animal',
    'corte de carne',
  ])),
  LottieRule('assets/gifs/microwave.gif', _keywords([
    'microondas',
    'calienta en microondas',
    'recalentar',
    'rapido en micro',
  ])),
  LottieRule('assets/gifs/milk.gif', _keywords([
    'leche',
    'milk',
    'añade leche',
    'vaso de leche',
  ])),
  LottieRule('assets/gifs/mixer.gif', _keywords([
    'mezclar',
    'batir',
    'remover',
    'mezclalo',
    'combinar',
    'incorporar',
    'batido espumoso',
  ])),
  LottieRule('assets/gifs/mushrooms.gif', _keywords([
    'hongos',
    'setas',
    'champinones',
    'mushrooms',
    'portobello',
  ])),
  LottieRule('assets/gifs/olives.gif', _keywords([
    'aceitunas',
    'olivas',
    'olives',
    'tapenade',
  ])),
  LottieRule('assets/gifs/onion.gif', _keywords([
    'cebolla',
    'onion',
    'cortar cebolla',
    'cebolla caramelizada',
  ])),
  LottieRule('assets/gifs/oven-mitt-glove-2.gif', _keywords([
    'guantes horno',
    'manopla',
    'proteccion horno',
    'guante térmico',
  ])),
  LottieRule('assets/gifs/oven-mitt-glove.gif', _keywords([
    'manopla horno',
    'guante cocina',
    'protector de horno',
  ])),
  LottieRule('assets/gifs/pan.gif', _keywords([
    'freir',
    'sarten',
    'plancha',
    'saltear',
    'dorar',
    'salteado rapido',
  ])),
  LottieRule('assets/gifs/pan-meat-vegetables-cooking.gif', _keywords([
    'saltear verduras',
    'mezclar en sarten',
    'cocinar carne y verduras',
    'salteado mixto',
  ])),
  LottieRule('assets/gifs/pancakes.gif', _keywords([
    'pancakes',
    'panqueques',
    'tortitas',
    'crepes americanas',
  ])),
  LottieRule('assets/gifs/pastry-bag.gif', _keywords([
    'manga pastelera',
    'decorar',
    'glasear',
    'pastry bag',
    'decoración fina',
  ])),
  LottieRule('assets/gifs/peanut-butter.gif', _keywords([
    'mantequilla de mani',
    'cacahuete',
    'untar',
    'peanut butter',
    'crema de cacahuate',
  ])),
  LottieRule('assets/gifs/pepper.gif', _keywords([
    'pimienta',
    'pimentero',
    'salpimentar',
    'pepper',
    'molinillo de pimienta',
  ])),
  LottieRule('assets/gifs/pizza-cutter.gif', _keywords([
    'cortador de pizza',
    'rueda de pizza',
    'pizza cutter',
    'cortar porciones',
  ])),
  LottieRule('assets/gifs/pizza.gif', _keywords([
    'pizza',
    'masa pizza',
    'hornear pizza',
    'pizzas artesanales',
  ])),
  LottieRule('assets/gifs/plant-based-steak.gif', _keywords([
    'carne vegetal',
    'plant based',
    'proteina vegetal',
    'filete vegano',
  ])),
  LottieRule('assets/gifs/plate-fork-knife.gif', _keywords([
    'servir',
    'emplatar',
    'presentar plato',
    'sirve',
    'montaje de plato',
  ])),
  LottieRule('assets/gifs/plate-pasta.gif', _keywords([
    'pasta',
    'spaghetti',
    'plato de pasta',
    'pasta al dente',
  ])),
  LottieRule('assets/gifs/plate-warm.gif', _keywords([
    'mantener caliente',
    'cubrir plato',
    'plate warmer',
    'guardar calor',
  ])),
  LottieRule('assets/gifs/professional-chef-knife.gif', _keywords([
    'cuchillo profesional',
    'filetear',
    'corte preciso',
    'herramienta chef',
  ])),
  LottieRule('assets/gifs/risotto-rice-dish.gif', _keywords([
    'risotto',
    'arroz cremoso',
    'plato de arroz',
    'risotto italiano',
  ])),
  LottieRule('assets/gifs/rolling-pin.gif', _keywords([
    'rodillo',
    'estirar masa',
    'rolling pin',
    'extender masa',
  ])),
  LottieRule('assets/gifs/salt-pepper.gif', _keywords([
    'salpimenta',
    'sal y pimienta',
    'seasoning',
    'condimenta',
  ])),
  LottieRule('assets/gifs/salt.gif', _keywords([
    'sal',
    'sal marina',
    'salar',
    'sal cristal',
    'sazonar con sal',
  ])),
  LottieRule('assets/gifs/sausage.gif', _keywords([
    'salchicha',
    'chorizo',
    'sausage',
    'embutido',
  ])),
  LottieRule('assets/gifs/scallops.gif', _keywords([
    'vieiras',
    'scallops',
    'marisco suave',
    'conchas finas',
  ])),
  LottieRule('assets/gifs/shortbread.gif', _keywords([
    'galleta de mantequilla',
    'shortbread',
    'masa quebrada',
    'galleta escocesa',
  ])),
  LottieRule('assets/gifs/shrimp.gif', _keywords([
    'camaron',
    'gamba',
    'shrimp',
    'langostino',
  ])),
  LottieRule('assets/gifs/spatula.gif', _keywords([
    'espátula',
    'espula',
    'gira',
    'spatula',
    'utensilio para voltear',
  ])),
  LottieRule('assets/gifs/spinach.gif', _keywords([
    'espinaca',
    'spinach',
    'verdura hoja verde',
    'hojas de espinaca',
  ])),
  LottieRule('assets/gifs/steak.gif', _keywords([
    'filete',
    'steak',
    'carne asada',
    'bistec a la parrilla',
  ])),
  LottieRule('assets/gifs/sushi.gif', _keywords([
    'sushi',
    'nigiri',
    'maki',
    'rollo sushi',
  ])),
  LottieRule('assets/gifs/taco.gif', _keywords([
    'taco',
    'tortilla',
    'mexicano',
    'street taco',
  ])),
  LottieRule('assets/gifs/toast-sandwich.gif', _keywords([
    'sandwich',
    'sándwich',
    'tostar sandwich',
    'sandwich mixto',
    'bocadillo caliente',
  ])),
  LottieRule('assets/gifs/toaster.gif', _keywords([
    'tostar',
    'tostador',
    'tostadora',
    'tostada',
    'desayuno tostado',
  ])),
  LottieRule('assets/gifs/toque-cooking-hat.gif', _keywords([
    'gorro de chef',
    'toque',
    'sombrero cocina',
    'gorra de cocinero',
  ])),
  LottieRule('assets/gifs/turkey.gif', _keywords([
    'pavo',
    'turkey',
    'hornear pavo',
    'pavo relleno',
  ])),
  LottieRule('assets/gifs/vege.gif', _keywords([
    'vegetales',
    'verduras',
    'vegetariano',
    'veggie',
    'mezcla de vegetales',
  ])),
  LottieRule('assets/gifs/waiter-restaurant.gif', _keywords([
    'camarero',
    'mesero',
    'waiter',
    'servicio sala',
    'atencion de mesa',
  ])),
  LottieRule('assets/gifs/wok.gif', _keywords([
    'wok',
    'saltear',
    'salteado asiatico',
    'salteo',
    'stir fry',
  ])),
];

List<String> _keywords(List<String> base) {
  final expanded = <String>{};
  for (final keyword in base) {
    final normalized = keyword.trim().toLowerCase();
    if (normalized.isEmpty) continue;
    expanded.add(normalized);

    final overrides = _keywordSynonyms[normalized];
    if (overrides != null) {
      for (final synonym in overrides) {
        final normalizedSynonym = synonym.trim().toLowerCase();
        if (normalizedSynonym.isNotEmpty) {
          expanded.add(normalizedSynonym);
        }
      }
    }

    for (final variant in _generateVariants(normalized)) {
      expanded.add(variant);
    }
  }

  return expanded.toList();
}

Iterable<String> _generateVariants(String keyword) {
  final variants = <String>{};
  if (!keyword.contains(' ')) {
    variants.addAll(_pluralForms(keyword));
    variants.addAll(_genderForms(keyword));
  } else {
    if (keyword.contains(' de ')) {
      variants.add(keyword.replaceAll(' de ', ' con '));
    }
    if (keyword.contains('-')) {
      variants.add(keyword.replaceAll('-', ' '));
    }
  }
  return variants;
}

Iterable<String> _pluralForms(String word) {
  final variants = <String>{};
  if (word.isEmpty) return variants;
  if (word.endsWith('s')) {
    variants.add(word);
    return variants;
  }

  if (_endsWithAny(word, ['ch', 'sh', 'x', 'z'])) {
    if (word.endsWith('z') && word.length > 1) {
      variants.add('${word.substring(0, word.length - 1)}ces');
    }
    variants.add('${word}es');
  } else if (word.endsWith('y') && word.length > 1 && _isConsonant(word[word.length - 2])) {
    variants.add('${word.substring(0, word.length - 1)}ies');
  } else if (_isVowel(word[word.length - 1])) {
    variants.add('${word}s');
  } else {
    variants.add('${word}es');
  }

  return variants;
}

Iterable<String> _genderForms(String word) {
  final variants = <String>{};
  if (word.endsWith('o')) {
    variants.add('${word}a');
  } else if (word.endsWith('a')) {
    variants.add('${word.substring(0, word.length - 1)}o');
  }
  return variants;
}

bool _isVowel(String char) => 'aeiouáéíóú'.contains(char);

bool _isConsonant(String char) => ! _isVowel(char);

bool _endsWithAny(String word, List<String> endings) =>
    endings.any((ending) => word.endsWith(ending));

const Map<String, List<String>> _keywordSynonyms = {
  'apple pie': ['tarta de manzana', 'pastel de manzana', 'pie de manzana'],
  'apple': ['apples', 'manzanas', 'fruta de manzana'],
  'manzana': ['manzanas', 'fruta roja', 'manzanita'],
  'tarta': ['tartas', 'torta', 'tarta dulce'],
  'pastel': ['pasteles', 'pastel dulce', 'pastelito'],
  'pie': ['pies', 'pastel americano'],
  'berenjena': ['berenjenas', 'berenjena morada'],
  'aubergine': ['aubergines'],
  'eggplant': ['eggplants'],
  'aguacate': ['aguacates', 'aguacatito'],
  'avocado': ['avocados'],
  'palta': ['paltas'],
  'patio': ['patios', 'terraza'],
  'jardin': ['jardines', 'jardin trasero'],
  'exterior': ['espacio exterior', 'aire libre'],
  'backyard': ['backyards'],
  'hornea': ['horneado', 'horneando'],
  'hornear': ['horneados', 'horneadas'],
  'horno': ['hornos', 'horno precalentado'],
  'precalienta': ['precalentado', 'precalentando'],
  'precalentar': ['precalentados'],
  'bake': ['baking', 'baked'],
  'cocer al horno': ['coccion al horno'],
  'barbacoa': ['barbacoas'],
  'barbecue': ['bbq', 'barbecues'],
  'parrilla': ['parrillas', 'asador'],
  'asar a la parrilla': ['grill'],
  'albahaca': ['hojas de albahaca', 'albahaca fresca'],
  'basil': ['fresh basil'],
  'hierbas frescas': ['hierbas recién cortadas'],
  'licua': ['licuando'],
  'licuado': ['licuados'],
  'licuadora': ['batidora', 'batidora de vaso'],
  'tritura': ['triturando'],
  'triturar': ['triturados'],
  'pure': ['puree'],
  'batido': ['batidos', 'smoothie'],
  'bol con palillos': ['tazon con palillos'],
  'chopsticks': ['pair of chopsticks'],
  'palillos': ['palillitos', 'palitos'],
  'ramen': ['ramen bowl'],
  'fideos': ['fideos orientales'],
  'sopa': ['sopita', 'caldito'],
  'caldo': ['caldos'],
  'sopera': ['sopera grande'],
  'sopero': ['bol sopero'],
  'hamburguesa': ['hamburguesas', 'hamburguesa doble'],
  'burger': ['burgers'],
  'sandwich de carne': ['sándwich de carne'],
  'carne molida': ['carne picada'],
  'mantequilla': ['mantequillas', 'manteca'],
  'butter': ['butters', 'buttery'],
  'untar mantequilla': ['untar pan'],
  'carbon': ['carbones'],
  'brasas': ['brasa'],
  'encender fuego': ['prender fuego'],
  'charcoal': ['charcoals'],
  'queso': ['quesos', 'queso derretido'],
  'cheese': ['cheeses', 'cheesy'],
  'rallar queso': ['queso rallado'],
  'comer con palillos': ['usar palillos'],
  'cuchillo grande': ['cuchillo pesado'],
  'hacha': ['hachuelas'],
  'cleaver': ['meat cleaver'],
  'picar carne gruesa': ['cortar carne gruesa'],
  'coco': ['cocos'],
  'coconut': ['coconuts'],
  'leche de coco': ['crema de coco'],
  'cafe': ['café', 'cafetito'],
  'cafetera': ['cafeteras'],
  'coffee': ['coffees'],
  'espresso': ['espressos'],
  'campana': ['campanas'],
  'extractor': ['extractores'],
  'cocina ventilacion': ['ventilador de cocina'],
  'galletas y leche': ['cookies and milk'],
  'merienda': ['snack vespertino'],
  'galletas': ['cookies', 'galletitas'],
  'hornear galletas': ['horneando galletas'],
  'delantal': ['delantales', 'mandil'],
  'apron': ['aprons'],
  'sacacorchos': ['saca corchos'],
  'vino': ['vinos', 'botella de vino'],
  'abrir botella': ['destapar botella'],
  'maiz': ['maíz', 'maicito'],
  'mazorca': ['mazorcas'],
  'corn': ['corns'],
  'corn dog': ['corn dogs'],
  'perrito de maiz': ['salchicha empanizada'],
  'hot dog de maiz': ['hot dog empanizado'],
  'expedicion': ['expediciones'],
  'aventura culinaria': ['tour gastronomico'],
  'heritage': ['heritage tour'],
  'viaje gastronomico': ['viajes culinarios'],
  'dona': ['donas'],
  'donut': ['donuts'],
  'rosquilla': ['rosquillas'],
  'huevera': ['hueveras'],
  'bandeja de huevos': ['bandejas de huevos'],
  'egg tray': ['egg trays'],
  'huevo': ['huevito'],
  'huevos': ['huevitos'],
  'rompe el huevo': ['cascar huevo'],
  'placa electrica': ['placas electricas'],
  'cocina electrica': ['cocinas electricas'],
  'stovetop': ['electric stovetop'],
  'vitroceramica': ['vitrocerámicas'],
  'hervidor': ['hervidores'],
  'tetera electrica': ['tetera eléctrica'],
  'electric kettle': ['electric kettles'],
  'te caliente': ['té caliente'],
  'comida rapida': ['comida rápida', 'fast food menu'],
  'combo': ['combos'],
  'cocinera': ['cocineras'],
  'chef mujer': ['chef femenina'],
  'female cook': ['female chef'],
  'suministros': ['stock de comida'],
  'provisiones': ['reserva de provisiones'],
  'despensa': ['despensas'],
  'abastece': ['abastecer'],
  'campana metalica': ['campana metálica'],
  'mantener caliente': ['mantener templado', 'mantener tibio'],
  'servir cubierto': ['servicio cubierto'],
  'camioneta de comida': ['truck de comida'],
  'food truck': ['food trucks'],
  'venta ambulante': ['puesto movil'],
  'tenedor y cuchillo': ['tenedor con cuchillo'],
  'cubre mesa': ['mesa puesta'],
  'cuberteria': ['cubertería', 'cubiertos'],
  'patatas fritas': ['papas fritas'],
  'papas fritas': ['papitas fritas'],
  'french fries': ['fries'],
  'macarons': ['macaron'],
  'macarrones franceses': ['macarron frances'],
  'dulce frances': ['dulce francés'],
  'nevera': ['neveritas'],
  'refrigerar': ['refrigerando'],
  'frigorifico': ['frigoríficos'],
  'enfria': ['enfriar'],
  'huevo frito': ['huevos fritos'],
  'fried egg': ['fried eggs'],
  'buñuelos': ['buñuelo'],
  'fritters': ['sweet fritters'],
  'freir masa': ['friendo masa'],
  'ajo': ['ajos', 'ajo picado'],
  'garlic': ['garlic clove'],
  'hervir': ['herviendo'],
  'ebullicion': ['ebulliciones'],
  'burbujea': ['burbujeando'],
  'fuego alto': ['llama alta'],
  'cocina de gas': ['cocinas de gas'],
  'fuego medio': ['fuego medio alto'],
  'gas': ['gas natural'],
  'pan de jengibre': ['panecillo de jengibre'],
  'gingerbread': ['gingerbreads'],
  'galleta de jengibre': ['galletas de jengibre'],
  'sin gluten': ['libre de gluten'],
  'gluten free': ['gluten-free'],
  'celiaco': ['celiacos'],
  'hierbas': ['hierbitas'],
  'herbs': ['herbal'],
  'aromaticas': ['aromáticas'],
  'miel': ['mieles'],
  'endulza con miel': ['endulzar con miel'],
  'hotdog': ['hotdogs'],
  'perro caliente': ['perros calientes'],
  'pancho': ['panchos'],
  'mermelada': ['mermeladas'],
  'confitura': ['confituras'],
  'jarra jam': ['jarra de mermelada'],
  'balanza': ['balanzas'],
  'peso': ['pesaje'],
  'pesar ingredientes': ['pesando ingredientes'],
  'cocina': ['cocinas'],
  'espacio cocina': ['area de cocina'],
  'cortar': ['cortando'],
  'cuchillo': ['cuchillos'],
  'picar': ['picado'],
  'trocear': ['troceado'],
  'juliana': ['cortar en juliana'],
  'rebanar': ['rebanado'],
  'cucharón': ['cucharones'],
  'cucharon': ['cucharones'],
  'servir sopa': ['servir la sopa'],
  'langosta': ['langostas'],
  'marisco': ['mariscos'],
  'lobster': ['lobsters'],
  'cocinero': ['cocineros'],
  'chef': ['chefs'],
  'molino de carne': ['molinos de carne'],
  'picadora': ['picadoras'],
  'grinder': ['grinders'],
  'carne': ['carnes'],
  'proteina animal': ['proteinas animales'],
  'microondas': ['microondas doméstico'],
  'calienta en microondas': ['calentar en microondas'],
  'recalentar': ['recalentado'],
  'leche': ['leches'],
  'añade leche': ['agrega leche'],
  'mezclar': ['mezclando'],
  'batir': ['batiendo'],
  'remover': ['removiendo'],
  'mezclalo': ['mezcla'],
  'combinar': ['combinado'],
  'incorporar': ['incorporado'],
  'hongos': ['honguitos'],
  'setas': ['setitas'],
  'champinones': ['champiñones'],
  'mushrooms': ['wild mushrooms'],
  'aceitunas': ['aceitunitas'],
  'olivas': ['olivitas'],
  'olives': ['olive'],
  'cebolla': ['cebollas'],
  'cortar cebolla': ['picando cebolla'],
  'guantes horno': ['guantes de horno'],
  'manopla': ['manoplas'],
  'proteccion horno': ['protección de horno'],
  'manopla horno': ['manoplas de horno'],
  'guante cocina': ['guantes de cocina'],
  'freir': ['friendo'],
  'sarten': ['sartén', 'sartenes'],
  'plancha': ['planchar la comida'],
  'saltear': ['salteado'],
  'dorar': ['dorando'],
  'saltear verduras': ['verduritas salteadas'],
  'mezclar en sarten': ['mezcla en la sartén'],
  'cocinar carne y verduras': ['salteo de carne y verduras'],
  'pancakes': ['pancake'],
  'panqueques': ['panqueque'],
  'tortitas': ['tortitas dulces'],
  'manga pastelera': ['mangas pasteleras'],
  'decorar': ['decorando'],
  'glasear': ['glaseado'],
  'pastry bag': ['pastry bags'],
  'mantequilla de mani': ['mantequilla de cacahuete'],
  'cacahuete': ['cacahuetes'],
  'untar': ['untando'],
  'peanut butter': ['peanut butters'],
  'pimienta': ['pimientas'],
  'pimentero': ['pimenteros'],
  'salpimentar': ['sazonar con pimienta'],
  'pepper': ['peppers'],
  'cortador de pizza': ['cortadores de pizza'],
  'rueda de pizza': ['ruedas de pizza'],
  'pizza cutter': ['pizza cutters'],
  'pizza': ['pizzas'],
  'masa pizza': ['masa para pizza'],
  'hornear pizza': ['horneando pizza'],
  'carne vegetal': ['carne vegana'],
  'plant based': ['plant-based'],
  'proteina vegetal': ['proteína vegetal'],
  'servir': ['sirviendo'],
  'emplatar': ['emplatado'],
  'presentar plato': ['presentación de plato'],
  'sirve': ['sirviendo'],
  'pasta': ['pastas'],
  'spaghetti': ['spaguetti', 'espagueti'],
  'plato de pasta': ['platos de pasta'],
  'cubrir plato': ['cubriendo plato'],
  'plate warmer': ['plate warmers'],
  'cuchillo profesional': ['cuchillos profesionales'],
  'filetear': ['fileteado'],
  'corte preciso': ['cortes precisos'],
  'risotto': ['risottos'],
  'arroz cremoso': ['arroz meloso'],
  'plato de arroz': ['platos de arroz'],
  'rolling pin': ['rolling pins'],
  'masa': ['masas'],
  'rodillo': ['rodillos'],
  'estirar masa': ['extendiendo masa'],
  'salpimenta': ['salpimentando'],
  'sal y pimienta': ['sal con pimienta'],
  'seasoning': ['seasonings'],
  'sal': ['sales'],
  'sal marina': ['sal gruesa'],
  'salar': ['sazonar'],
  'sausage': ['sausages'],
  'salchicha': ['salchichas'],
  'chorizo': ['chorizos'],
  'vieiras': ['vieira'],
  'scallops': ['sea scallops'],
  'marisco suave': ['marisco delicado'],
  'galleta de mantequilla': ['galletas de mantequilla'],
  'shortbread': ['shortbreads'],
  'masa quebrada': ['masa sablee'],
  'camaron': ['camarones'],
  'gamba': ['gambas'],
  'shrimp': ['shrimps'],
  'espátula': ['espatulas'],
  'gira': ['dar la vuelta'],
  'spatula': ['kitchen spatula'],
  'espinaca': ['espinacas'],
  'spinach': ['baby spinach'],
  'verdura hoja verde': ['verduras de hoja'],
  'filete': ['filetes'],
  'steak': ['steaks'],
  'carne asada': ['carne a la parrilla'],
  'sushi': ['sushis'],
  'nigiri': ['nigiris'],
  'maki': ['makis'],
  'taco': ['tacos'],
  'tortilla': ['tortillas'],
  'mexicano': ['estilo mexicano'],
  'sandwich': ['sandwiches'],
  'sándwich': ['sándwiches'],
  'tostar sandwich': ['tostando sandwich'],
  'sandwich mixto': ['sandwich caliente'],
  'tostar': ['tostando'],
  'tostador': ['tostadores'],
  'tostadora': ['tostadoras'],
  'tostada': ['tostadas'],
  'gorro de chef': ['gorro de cocinero'],
  'toque': ['toques'],
  'sombrero cocina': ['sombreros de cocina'],
  'pavo': ['pavos'],
  'turkey': ['turkeys'],
  'hornear pavo': ['pavo al horno'],
  'vegetales': ['vegetalitos'],
  'verduras': ['verduras frescas'],
  'vegetariano': ['vegetarianos'],
  'veggie': ['veggies'],
  'camarero': ['camareros'],
  'mesero': ['meseros'],
  'waiter': ['waiters'],
  'servicio sala': ['servicio de mesa'],
  'wok': ['woks'],
  'salteado asiatico': ['salteado asiático'],
  'salteo': ['salteos'],
  'stir fry': ['stir-fry'],
};
